create table file_path(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    file_path_prefix text,
    storage_name text,
    user_id BIGINT,
    file_name text,
    constraint file_path_pk primary key (id)
);