create table IF NOT EXISTS  photo_path_win
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    file_path_prefix VARCHAR(250),
    storage_name VARCHAR(250),
    user_id BIGINT,
    file_name VARCHAR(250),
    constraint photo_path_win_pk primary key (id)
);

create table IF NOT EXISTS  tags
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tag VARCHAR(250),
    constraint tags_pk primary key (id),
    constraint unique_tag UNIQUE (tag)
);

create table IF NOT EXISTS  photo_path_win_to_tags
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    photo_id BIGINT,
    tag_id BIGINT,
    constraint photo_path_win_to_tags_pk primary key (id),
    constraint photo_id_fk foreign key (photo_id) references photo_path_win,
    constraint tag_id_fk foreign key (tag_id) references tags
);
